### ISSUE TITLE
오류가 생겼습니다

### ISSUE THREAD

**Issue by Hyeongu02** [DetegiCE/XIN_Picture_Downloader#1]
Traceback (most recent call last):
  File "C:\Users\rkdgu\Desktop\XIN_Picture_Downloader-master\main.py", line 4, in <module>
    url = getpics.getUrl("./data/xinhtml.txt")
  File "C:\Users\rkdgu\Desktop\XIN_Picture_Downloader-master\getpics.py", line 9, in getUrl
    atxt = f.read()
UnicodeDecodeError: 'cp949' codec can't decode byte 0xec in position 399: illegal multibyte sequence
라고 뜨면서 다운이 안되네요 혹시 pillow를 다운할떄 https://blog.naver.com/youngayo1/221800375340 방식으로 했는데 이게 문제인가요?

**Comment by DetegiCE** [comment]
@chickenisgood 파일 읽어올 때 발생한 문제 같습니다
``getpics.py`` 파일 8번 줄의 `f = open(file, "r")`를 `f = open(file, "r", encoding="UTF8")` 로 바꿔주세요

**Comment by Hyeongu02** [comment]
바꿔주니 실행이 잘되었습니다 하지만 강의 시간이 50분이지만 다운받은 음성파일은 25분밖에 다운이 안되는데 최대시간이 있는건가요?

**Comment by DetegiCE** [comment]
@chickenisgood 시간 제한은 없습니다 음성파일이 절반밖에 다운되지 않은거는 저도 잘 모르겠네요

**Comment by chickenisgood** [comment]
Pictures Downloading...
Traceback (most recent call last):
  File "C:\Users\rkdgu\Desktop\XIN_Picture_Downloader-master\main.py", line 4, in <module>
    url = getpics.getUrl("./data/xinhtml.txt")
  File "C:\Users\rkdgu\Desktop\XIN_Picture_Downloader-master\getpics.py", line 33, in getUrl
    im1.save("./download/slide.pdf", save_all=True, append_images=imgs)
UnboundLocalError: local variable 'im1' referenced before assignment
라는 오류가 뜹니다. 어떻게 해야할까요?
